name: BedWars
version: 1.0
api-version: 1.16
main: me.mrfunny.plugins.paper.BedWars

depend: [ExampleJScoreboardPlugin]

permissions:
  bedwars.admin:
    default: false

commands:
  setup:
    permission: bedwars.admin
  start:
    permission: bedwars.admin